export const COUNT_ALL_STUDENTS_REQUEST = "COUNT_ALL_STUDENTS_REQUEST";
export const COUNT_ALL_STUDENTS_SUCCESS = "COUNT_ALL_STUDENTS_SUCCESS";
export const COUNT_ALL_STUDENTS_FAILURE = "COUNT_ALL_STUDENTS_FAILURE";

export const COUNT_ALL_TEACHERS_REQUEST = "COUNT_ALL_TEACHERS_REQUEST";
export const COUNT_ALL_TEACHERS_SUCCESS = "COUNT_ALL_TEACHERS_SUCCESS";
export const COUNT_ALL_TEACHERS_FAILURE = "COUNT_ALL_TEACHERS_FAILURE";

export const COUNT_ALL_STUDENT_SEMESTERS_REQUEST =
  "COUNT_ALL_STUDENT_SEMESTERS_REQUEST";
export const COUNT_ALL_STUDENT_SEMESTERS_SUCCESS =
  "COUNT_ALL_STUDENT_SEMESTERS_SUCCESS";
export const COUNT_ALL_STUDENT_SEMESTERS_FAILURE =
  "COUNT_ALL_STUDENT_SEMESTERS_FAILURE";

export const COUNT_ALL_REGISTERED_PROJECT_STUDENT_REQUEST =
  "COUNT_ALL_REGISTERED_PROJECT_STUDENT_REQUEST";
export const COUNT_ALL_REGISTERED_PROJECT_STUDENT_SUCCESS =
  "COUNT_ALL_REGISTERED_PROJECT_STUDENT_SUCCESS";
export const COUNT_ALL_REGISTERED_PROJECT_STUDENT_FAILURE =
  "COUNT_ALL_REGISTERED_PROJECT_STUDENT_FAILURE";
