export const GET_STUDENT_BY_STUDENTCODE_REQUEST =
  "GET_STUDENT_BY_STUDENTCODE_REQUEST";
export const GET_STUDENT_BY_STUDENTCODE_SUCCESS =
  "GET_STUDENT_BY_STUDENTCODE_SUCCESS";
export const GET_STUDENT_BY_STUDENTCODE_FAILURE =
  "GET_STUDENT_BY_STUDENTCODE_FAILURE";

export const FILTER_ALL_STUDENTS_REQUEST = "FILTER_ALL_STUDENTS_REQUEST";
export const FILTER_ALL_STUDENTS_SUCCESS = "FILTER_ALL_STUDENTS_SUCCESS";
export const FILTER_ALL_STUDENTS_FAILURE = "FILTER_ALL_STUDENTS_FAILURE";

export const GET_INSTRUCTOR_BY_STUDENTID_IN_CURRENT_SEMESTER_REQUEST =
  "GET_INSTRUCTOR_BY_STUDENTID_IN_CURRENT_SEMESTER_REQUEST";
export const GET_INSTRUCTOR_BY_STUDENTID_IN_CURRENT_SEMESTER_SUCCESS =
  "GET_INSTRUCTOR_BY_STUDENTID_IN_CURRENT_SEMESTER_SUCCESS";
export const GET_INSTRUCTOR_BY_STUDENTID_IN_CURRENT_SEMESTER_FAILURE =
  "GET_INSTRUCTOR_BY_STUDENTID_IN_CURRENT_SEMESTER_FAILURE";

export const UPDATE_ENABLE_STATUS_REQUEST = "UPDATE_ENABLE_STATUS_REQUEST";
export const UPDATE_ENABLE_STATUS_SUCCESS = "UPDATE_ENABLE_STATUS_SUCCESS";
export const UPDATE_ENABLE_STATUS_FAILURE = "UPDATE_ENABLE_STATUS_FAILURE";

export const GET_ALL_STUDENTS_ACCOUNT_REQUEST =
  "GET_ALL_STUDENTS_ACCOUNT_REQUEST";
export const GET_ALL_STUDENTS_ACCOUNT_SUCCESS =
  "GET_ALL_STUDENTS_ACCOUNT_SUCCESS";
export const GET_ALL_STUDENTS_ACCOUNT_FAILURE =
  "GET_ALL_STUDENTS_ACCOUNT_FAILURE";

export const CREATE_STUDENT_ACCOUNT_REQUEST = "CREATE_STUDENT_ACCOUNT_REQUEST";
export const CREATE_STUDENT_ACCOUNT_SUCCESS = "CREATE_STUDENT_ACCOUNT_SUCCESS";
export const CREATE_STUDENT_ACCOUNT_FAILURE = "CREATE_STUDENT_ACCOUNT_FAILURE";

export const UPDATE_STUDENT_ACCOUNT_REQUEST = "UPDATE_STUDENT_ACCOUNT_REQUEST";
export const UPDATE_STUDENT_ACCOUNT_SUCCESS = "UPDATE_STUDENT_ACCOUNT_SUCCESS";
export const UPDATE_STUDENT_ACCOUNT_FAILURE = "UPDATE_STUDENT_ACCOUNT_FAILURE";

// FOR MANAGING REGISTERED STUDENT
export const GET_ALL_STUDENTS_NOT_ENROLLED_IN_CURRENT_SEMESTER_REQUEST =
  "GET_ALL_STUDENTS_NOT_ENROLLED_IN_CURRENT_SEMESTER_REQUEST";
export const GET_ALL_STUDENTS_NOT_ENROLLED_IN_CURRENT_SEMESTER_SUCCESS =
  "GET_ALL_STUDENTS_NOT_ENROLLED_IN_CURRENT_SEMESTER_SUCCESS";
export const GET_ALL_STUDENTS_NOT_ENROLLED_IN_CURRENT_SEMESTER_FAILURE =
  "GET_ALL_STUDENTS_NOT_ENROLLED_IN_CURRENT_SEMESTER_FAILURE";

export const CHOOSE_STUDENT_REQUEST = "CHOOSE_STUDENT_REQUEST";
export const CHOOSE_STUDENT_SUCCESS = "CHOOSE_STUDENT_SUCCESS";
export const CHOOSE_STUDENT_FAILURE = "CHOOSE_STUDENT_FAILURE";

export const REMOVE_STUDENT_FROM_TEMPORARY_LIST_REQUEST =
  "REMOVE_STUDENT_FROM_TEMPORARY_LIST_REQUEST";
export const REMOVE_STUDENT_FROM_TEMPORARY_LIST_SUCCESS =
  "REMOVE_STUDENT_FROM_TEMPORARY_LIST_SUCCESS";
export const REMOVE_STUDENT_FROM_TEMPORARY_LIST_FAILURE =
  "REMOVE_STUDENT_FROM_TEMPORARY_LIST_FAILURE";

export const ADD_STUDENT_TO_CURRENT_SEMESTER_REQUEST =
  "ADD_STUDENT_TO_CURRENT_SEMESTER_REQUEST";
export const ADD_STUDENT_TO_CURRENT_SEMESTER_SUCCESS =
  "ADD_STUDENT_TO_CURRENT_SEMESTER_SUCCESS";
export const ADD_STUDENT_TO_CURRENT_SEMESTER_FAILURE =
  "ADD_STUDENT_TO_CURRENT_SEMESTER_FAILURE";

export const DELETE_STUDENT_IN_CURRENT_SEMESTER_REQUEST =
  "DELETE_STUDENT_IN_CURRENT_SEMESTER_REQUEST";
export const DELETE_STUDENT_IN_CURRENT_SEMESTER_SUCCESS =
  "DELETE_STUDENT_IN_CURRENT_SEMESTER_SUCCESS";
export const DELETE_STUDENT_IN_CURRENT_SEMESTER_FAILURE =
  "DELETE_STUDENT_IN_CURRENT_SEMESTER_FAILURE";
