export const GET_STUDENTS_BY_FACULTY_AND_KEYWORD_REQUEST =
  "GET_STUDENTS_BY_FACULTY_AND_KEYWORD_REQUEST";
export const GET_STUDENTS_BY_FACULTY_AND_KEYWORD_SUCCESS =
  "GET_STUDENTS_BY_FACULTY_AND_KEYWORD_SUCCESS";
export const GET_STUDENTS_BY_FACULTY_AND_KEYWORD_FAILURE =
  "GET_STUDENTS_BY_FACULTY_AND_KEYWORD_FAILURE";
