export const FILTER_ALL_STUDENTS_REQUEST = "FILTER_ALL_STUDENTS_REQUEST";
export const FILTER_ALL_STUDENTS_SUCCESS = "FILTER_ALL_STUDENTS_SUCCESS";
export const FILTER_ALL_STUDENTS_FAILURE = "FILTER_ALL_STUDENTS_FAILURE";
