export const GET_CHATROOM_BY_TEAMID_REQUEST = "GET_CHATROOM_BY_TEAMID_REQUEST";
export const GET_CHATROOM_BY_TEAMID_SUCCESS = "GET_CHATROOM_BY_TEAMID_SUCCESS";
export const GET_CHATROOM_BY_TEAMID_FAILURE = "GET_CHATROOM_BY_TEAMID_FAILURE";

export const GET_CHATMESSAGES_BY_TEAMID_REQUEST =
  "GET_CHATMESSAGES_BY_TEAMID_REQUEST";
export const GET_CHATMESSAGES_BY_TEAMID_SUCCESS =
  "GET_CHATMESSAGES_BY_TEAMID_SUCCESS";
export const GET_CHATMESSAGES_BY_TEAMID_FAILURE =
  "GET_CHATMESSAGES_BY_TEAMID_FAILURE";

export const GET_CHAT_MESSAGES_BY_PROJECT_ID_REQUEST =
  "GET_CHAT_MESSAGES_BY_PROJECT_ID_REQUEST";
export const GET_CHAT_MESSAGES_BY_PROJECT_ID_SUCCESS =
  "GET_CHAT_MESSAGES_BY_PROJECT_ID_SUCCESS";
export const GET_CHAT_MESSAGES_BY_PROJECT_ID_FAILURE =
  "GET_CHAT_MESSAGES_BY_PROJECT_ID_FAILURE";
