export const GET_PROJECT_BY_PROJECTID_REQUEST =
  "GET_PROJECT_BY_PROJECTID_REQUEST";
export const GET_PROJECT_BY_PROJECTID_SUCCESS =
  "GET_PROJECT_BY_PROJECTID_SUCCESS";
export const GET_PROJECT_BY_PROJECTID_FAILURE =
  "GET_PROJECT_BY_PROJECTID_FAILURE";

export const GET_ALL_STAGES_BY_PROJECT_REQUEST =
  "GET_ALL_STAGES_BY_PROJECT_REQUEST";
export const GET_ALL_STAGES_BY_PROJECT_SUCCESS =
  "GET_ALL_STAGES_BY_PROJECT_SUCCESS";
export const GET_ALL_STAGES_BY_PROJECT_FAILURE =
  "GET_ALL_STAGES_BY_PROJECT_FAILURE";

export const GET_ALL_PROGRESSREPORTS_BY_PROJECT_REQUEST =
  "GET_ALL_PROGRESSREPORTS_BY_PROJECT_REQUEST";
export const GET_ALL_PROGRESSREPORTS_BY_PROJECT_SUCCESS =
  "GET_ALL_PROGRESSREPORTS_BY_PROJECT_SUCCESS";
export const GET_ALL_PROGRESSREPORTS_BY_PROJECT_FAILURE =
  "GET_ALL_PROGRESSREPORTS_BY_PROJECT_FAILURE";

export const GET_PROGRESS_REPORT_BY_ID_REQUEST =
  "GET_PROGRESS_REPORT_BY_ID_REQUEST";
export const GET_PROGRESS_REPORT_BY_ID_SUCCESS =
  "GET_PROGRESS_REPORT_BY_ID_SUCCESS";
export const GET_PROGRESS_REPORT_BY_ID_FAILURE =
  "GET_PROGRESS_REPORT_BY_ID_FAILURE";

export const GET_PROGRESS_REVIEW_BY_ID_REQUEST =
  "GET_PROGRESS_REVIEW_BY_ID_REQUEST";
export const GET_PROGRESS_REVIEW_BY_ID_SUCCESS =
  "GET_PROGRESS_REVIEW_BY_ID_SUCCESS";
export const GET_PROGRESS_REVIEW_BY_ID_FAILURE =
  "GET_PROGRESS_REVIEW_BY_ID_FAILURE";

export const DELETE_PROGRESS_REVIEW_FILE_BY_ID_REQUEST =
  "DELETE_PROGRESS_REVIEW_FILE_BY_ID_REQUEST";
export const DELETE_PROGRESS_REVIEW_FILE_BY_ID_SUCCESS =
  "DELETE_PROGRESS_REVIEW_FILE_BY_ID_SUCCESS";
export const DELETE_PROGRESS_REVIEW_FILE_BY_ID_FAILURE =
  "DELETE_PROGRESS_REVIEW_FILE_BY_ID_FAILURE";

export const CREATE_PROGRESS_REVIEW_REQUEST = "CREATE_PROGRESS_REVIEW_REQUEST";
export const CREATE_PROGRESS_REVIEW_SUCCESS = "CREATE_PROGRESS_REVIEW_SUCCESS";
export const CREATE_PROGRESS_REVIEW_FAILURE = "CREATE_PROGRESS_REVIEW_FAILURE";

export const UPDATE_PROGRESS_REVIEW_REQUEST = "UPDATE_PROGRESS_REVIEW_REQUEST";
export const UPDATE_PROGRESS_REVIEW_SUCCESS = "UPDATE_PROGRESS_REVIEW_SUCCESS";
export const UPDATE_PROGRESS_REVIEW_FAILURE = "UPDATE_PROGRESS_REVIEW_FAILURE";

export const DELETE_PROGRESS_REVIEW_BY_ID_REQUEST =
  "DELETE_PROGRESS_REVIEW_BY_ID_REQUEST";
export const DELETE_PROGRESS_REVIEW_BY_ID_SUCCESS =
  "DELETE_PROGRESS_REVIEW_BY_ID_SUCCESS";
export const DELETE_PROGRESS_REVIEW_BY_ID_FAILURE =
  "DELETE_PROGRESS_REVIEW_BY_ID_FAILURE";
