export const GET_ALL_PROJECTS_BY_INSTRUCTOR_REQUEST =
  "GET_ALL_PROJECTS_BY_INSTRUCTOR_REQUEST";
export const GET_ALL_PROJECTS_BY_INSTRUCTOR_SUCCESS =
  "GET_ALL_PROJECTS_BY_INSTRUCTOR_SUCCESS";
export const GET_ALL_PROJECTS_BY_INSTRUCTOR_FAILURE =
  "GET_ALL_PROJECTS_BY_INSTRUCTOR_FAILURE";

export const GET_PROJECT_BY_STUDENTCODE_REQUEST =
  "GET_PROJECT_BY_STUDENTCODE_REQUEST";
export const GET_PROJECT_BY_STUDENTCODE_SUCCESS =
  "GET_PROJECT_BY_STUDENTCODE_SUCCESS";
export const GET_PROJECT_BY_STUDENTCODE_FAILURE =
  "GET_PROJECT_BY_STUDENTCODE_FAILURE";

export const APPROVE_PROJECT_REQUEST = "APPROVE_PROJECT_REQUEST";
export const APPROVE_PROJECT_SUCCESS = "APPROVE_PROJECT_SUCCESS";
export const APPROVE_PROJECT_FAILURE = "APPROVE_PROJECT_FAILURE";

export const DECLINE_PROJECT_REQUEST = "DECLINE_PROJECT_REQUEST";
export const DECLINE_PROJECT_SUCCESS = "DECLINE_PROJECT_SUCCESS";
export const DECLINE_PROJECT_FAILURE = "DECLINE_PROJECT_FAILURE";
