export const GET_ALL_SCHOOL_YEAR_REQUEST = "GET_ALL_SCHOOL_YEAR_REQUEST";
export const GET_ALL_SCHOOL_YEAR_SUCCESS = "GET_ALL_SCHOOL_YEAR_SUCCESS";
export const GET_ALL_SCHOOL_YEAR_FAILURE = "GET_ALL_SCHOOL_YEAR_FAILURE";

export const CREATE_SCHOOL_YEAR_REQUEST = "CREATE_SCHOOL_YEAR_REQUEST";
export const CREATE_SCHOOL_YEAR_SUCCESS = "CREATE_SCHOOL_YEAR_SUCCESS";
export const CREATE_SCHOOL_YEAR_FAILURE = "CREATE_SCHOOL_YEAR_FAILURE";

export const DELETE_SCHOOL_YEAR_REQUEST = "DELETE_SCHOOL_YEAR_REQUEST";
export const DELETE_SCHOOL_YEAR_SUCCESS = "DELETE_SCHOOL_YEAR_SUCCESS";
export const DELETE_SCHOOL_YEAR_FAILURE = "DELETE_SCHOOL_YEAR_FAILURE";

export const GET_SCHOOL_YEAR_BY_ID_REQUEST = "GET_SCHOOL_YEAR_BY_ID_REQUEST";
export const GET_SCHOOL_YEAR_BY_ID_SUCCESS = "GET_SCHOOL_YEAR_BY_ID_SUCCESS";
export const GET_SCHOOL_YEAR_BY_ID_FAILURE = "GET_SCHOOL_YEAR_BY_ID_FAILURE";

export const UPDATE_SCHOOL_YEAR_REQUEST = "UPDATE_SCHOOL_YEAR_REQUEST";
export const UPDATE_SCHOOL_YEAR_SUCCESS = "UPDATE_SCHOOL_YEAR_SUCCESS";
export const UPDATE_SCHOOL_YEAR_FAILURE = "UPDATE_SCHOOL_YEAR_FAILURE";
