export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAILURE = "CREATE_PROJECT_FAILURE";

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE";

export const GET_PROJECT_BY_STUDENTCODE_REQUEST =
  "GET_PROJECT_BY_STUDENTCODE_REQUEST";
export const GET_PROJECT_BY_STUDENTCODE_SUCCESS =
  "GET_PROJECT_BY_STUDENTCODE_SUCCESS";
export const GET_PROJECT_BY_STUDENTCODE_FAILURE =
  "GET_PROJECT_BY_STUDENTCODE_FAILURE";

export const GET_INSTRUCTOR_OF_PROJECT_BY_STUDENTCODE_REQUEST =
  "GET_INSTRUCTOR_OF_PROJECT_BY_STUDENTCODE_REQUEST";
export const GET_INSTRUCTOR_OF_PROJECT_BY_STUDENTCODE_SUCCESS =
  "GET_INSTRUCTOR_OF_PROJECT_BY_STUDENTCODE_SUCCESS";
export const GET_INSTRUCTOR_OF_PROJECT_BY_STUDENTCODE_FAILURE =
  "GET_INSTRUCTOR_OF_PROJECT_BY_STUDENTCODE_FAILURE";

export const DELETE_PROJECT_FILE_BY_ID_REQUEST =
  "DELETE_PROJECT_FILE_BY_ID_REQUEST";
export const DELETE_PROJECT_FILE_BY_ID_SUCCESS =
  "DELETE_PROJECT_FILE_BY_ID_SUCCESS";
export const DELETE_PROJECT_FILE_BY_ID_FAILURE =
  "DELETE_PROJECT_FILE_BY_ID_FAILURE";
