export const GET_ALL_STAGES_BY_PROJECT_REQUEST =
  "GET_ALL_STAGES_BY_PROJECT_REQUEST";
export const GET_ALL_STAGES_BY_PROJECT_SUCCESS =
  "GET_ALL_STAGES_BY_PROJECT_SUCCESS";
export const GET_ALL_STAGES_BY_PROJECT_FAILURE =
  "GET_ALL_STAGES_BY_PROJECT_FAILURE";

export const GET_STAGE_BY_ID_REQUEST = "GET_STAGE_BY_ID_REQUEST";
export const GET_STAGE_BY_ID_SUCCESS = "GET_STAGE_BY_ID_SUCCESS";
export const GET_STAGE_BY_ID_FAILURE = "GET_STAGE_BY_ID_FAILURE";

export const GET_ALL_PROGRESSREPORTS_BY_PROJECT_REQUEST =
  "GET_ALL_PROGRESSREPORTS_BY_PROJECT_REQUEST";
export const GET_ALL_PROGRESSREPORTS_BY_PROJECT_SUCCESS =
  "GET_ALL_PROGRESSREPORTS_BY_PROJECT_SUCCESS";
export const GET_ALL_PROGRESSREPORTS_BY_PROJECT_FAILURE =
  "GET_ALL_PROGRESSREPORTS_BY_PROJECT_FAILURE";

export const GET_PROGRESSREPORT_BY_ID_REQUEST =
  "GET_PROGRESSREPORT_BY_ID_REQUEST";
export const GET_PROGRESSREPORT_BY_ID_SUCCESS =
  "GET_PROGRESSREPORT_BY_ID_SUCCESS";
export const GET_PROGRESSREPORT_BY_ID_FAILURE =
  "GET_PROGRESSREPORT_BY_ID_FAILURE";

export const CREATE_PROGRESSREPORT_REQUEST = "CREATE_PROGRESSREPORT_REQUEST";
export const CREATE_PROGRESSREPORT_SUCCESS = "CREATE_PROGRESSREPORT_SUCCESS";
export const CREATE_PROGRESSREPORT_FAILURE = "CREATE_PROGRESSREPORT_FAILURE";

export const UPDATE_PROGRESSREPORT_REQUEST = "UPDATE_PROGRESSREPORT_REQUEST";
export const UPDATE_PROGRESSREPORT_SUCCESS = "UPDATE_PROGRESSREPORT_SUCCESS";
export const UPDATE_PROGRESSREPORT_FAILURE = "UPDATE_PROGRESSREPORT_FAILURE";

export const DELETE_PROGRESSREPORT_REQUEST = "DELETE_PROGRESSREPORT_REQUEST";
export const DELETE_PROGRESSREPORT_SUCCESS = "DELETE_PROGRESSREPORT_SUCCESS";
export const DELETE_PROGRESSREPORT_FAILURE = "DELETE_PROGRESSREPORT_FAILURE";

export const DELETE_PROGRESSREPORTFILE_BY_ID_REQUEST =
  "DELETE_PROGRESSREPORTFILE_BY_ID_REQUEST";
export const DELETE_PROGRESSREPORTFILE_BY_ID_SUCCESS =
  "DELETE_PROGRESSREPORTFILE_BY_ID_SUCCESS";
export const DELETE_PROGRESSREPORTFILE_BY_ID_FAILURE =
  "DELETE_PROGRESSREPORTFILE_BY_ID_FAILURE";

export const GET_CURRENT_STAGE_BY_PROJECT_ID_REQUEST =
  "GET_CURRENT_STAGE_BY_PROJECT_ID_REQUEST";
export const GET_CURRENT_STAGE_BY_PROJECT_ID_SUCCESS =
  "GET_CURRENT_STAGE_BY_PROJECT_ID_SUCCESS";
export const GET_CURRENT_STAGE_BY_PROJECT_ID_FAILURE =
  "GET_CURRENT_STAGE_BY_PROJECT_ID_FAILURE";
