export const GET_ALL_STUDENTS_BY_INSTRUCTOR_REQUEST =
  "GET_ALL_STUDENTS_BY_INSTRUCTOR_REQUEST";
export const GET_ALL_STUDENTS_BY_INSTRUCTOR_SUCCESS =
  "GET_ALL_STUDENTS_BY_INSTRUCTOR_SUCCESS";
export const GET_ALL_STUDENTS_BY_INSTRUCTOR_FAILURE =
  "GET_ALL_STUDENTS_BY_INSTRUCTOR_FAILURE";

export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_REQUEST =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_REQUEST";
export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_SUCCESS =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_SUCCESS";
export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_FAILURE =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_FAILURE";

export const GET_ALL_TEACHERS_REQUEST = "GET_ALL_TEACHERS_REQUEST";
export const GET_ALL_TEACHERS_SUCCESS = "GET_ALL_TEACHERS_SUCCESS";
export const GET_ALL_TEACHERS_FAILURE = "GET_ALL_TEACHERS_FAILURE";

export const CREATE_TEACHER_REQUEST = "CREATE_TEACHER_REQUEST";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAILURE = "CREATE_TEACHER_FAILURE";
