export const GET_ALL_STUDENTS_BY_INSTRUCTOR_REQUEST =
  "GET_ALL_STUDENTS_BY_INSTRUCTOR_REQUEST";
export const GET_ALL_STUDENTS_BY_INSTRUCTOR_SUCCESS =
  "GET_ALL_STUDENTS_BY_INSTRUCTOR_SUCCESS";
export const GET_ALL_STUDENTS_BY_INSTRUCTOR_FAILURE =
  "GET_ALL_STUDENTS_BY_INSTRUCTOR_FAILURE";

export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_REQUEST =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_REQUEST";
export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_SUCCESS =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_SUCCESS";
export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_FAILURE =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_FAILURE";
