export const ADD_STUDENT_TO_TEAM_REQUEST = "ADD_STUDENT_TO_TEAM_REQUEST";
export const ADD_STUDENT_TO_TEAM_SUCCESS = "ADD_STUDENT_TO_TEAM_SUCCESS";
export const ADD_STUDENT_TO_TEAM_FAILURE = "ADD_STUDENT_TO_TEAM_FAILURE";

export const REMOVE_STUDENT_FROM_TEAM_REQUEST =
  "REMOVE_STUDENT_FROM_TEAM_REQUEST";
export const REMOVE_STUDENT_FROM_TEAM_SUCCESS =
  "REMOVE_STUDENT_FROM_TEAM_SUCCESS";
export const REMOVE_STUDENT_FROM_TEAM_FAILURE =
  "REMOVE_STUDENT_FROM_TEAM_FAILURE";
