export const GET_ALL_TEACHERS_BY_FACULTY_REQUEST =
  "GET_ALL_TEACHERS_BY_FACULTY_REQUEST";
export const GET_ALL_TEACHERS_BY_FACULTY_SUCCESS =
  "GET_ALL_TEACHERS_BY_FACULTY_SUCCESS";
export const GET_ALL_TEACHERS_BY_FACULTY_FAILURE =
  "GET_ALL_TEACHERS_BY_FACULTY_FAILURE";

export const GET_ALL_RECOMMENDED_TEACHER_REQUEST =
  "GET_ALL_RECOMMENDED_TEACHER_REQUEST";
export const GET_ALL_RECOMMENDED_TEACHER_SUCCESS =
  "GET_ALL_RECOMMENDED_TEACHER_SUCCESS";
export const GET_ALL_RECOMMENDED_TEACHER_FAILURE =
  "GET_ALL_RECOMMENDED_TEACHER_FAILURE";

export const ADD_RECOMMENDED_TEACHER_REQUEST =
  "ADD_RECOMMENDED_TEACHER_REQUEST";
export const ADD_RECOMMENDED_TEACHER_SUCCESS =
  "ADD_RECOMMENDED_TEACHER_SUCCESS";
export const ADD_RECOMMENDED_TEACHER_FAILURE =
  "ADD_RECOMMENDED_TEACHER_FAILURE";

export const REMOVE_RECOMMENDED_TEACHER_REQUEST =
  "REMOVE_RECOMMENDED_TEACHER_REQUEST";
export const REMOVE_RECOMMENDED_TEACHER_SUCCESS =
  "REMOVE_RECOMMENDED_TEACHER_SUCCESS";
export const REMOVE_RECOMMENDED_TEACHER_FAILURE =
  "REMOVE_RECOMMENDED_TEACHER_FAILURE";
