export const GET_ALL_CLASSES_REQUEST = "GET_ALL_CLASSES_REQUEST";
export const GET_ALL_CLASSES_SUCCESS = "GET_ALL_CLASSES_SUCCESS";
export const GET_ALL_CLASSES_FAILURE = "GET_ALL_CLASSES_FAILURE";

export const GET_ALL_CLASSES_BY_FACULTY_REQUEST =
  "GET_ALL_CLASSES_BY_FACULTY_REQUEST";
export const GET_ALL_CLASSES_BY_FACULTY_SUCCESS =
  "GET_ALL_CLASSES_BY_FACULTY_SUCCESS";
export const GET_ALL_CLASSES_BY_FACULTY_FAILURE =
  "GET_ALL_CLASSES_BY_FACULTY_FAILURE";
