export const GET_ALL_STUDENTS_WITHOUT_INSTRUCTOR_REQUEST =
  "GET_ALL_STUDENTS_WITHOUT_INSTRUCTOR_REQUEST";
export const GET_ALL_STUDENTS_WITHOUT_INSTRUCTOR_SUCCESS =
  "GET_ALL_STUDENTS_WITHOUT_INSTRUCTOR_SUCCESS";
export const GET_ALL_STUDENTS_WITHOUT_INSTRUCTOR_FAILURE =
  "GET_ALL_STUDENTS_WITHOUT_INSTRUCTOR_FAILURE";

export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_LEADER_REQUEST =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_LEADER_REQUEST";
export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_LEADER_SUCCESS =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_LEADER_SUCCESS";
export const GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_LEADER_FAILURE =
  "GET_ALL_CLASSES_BY_FACULTY_OF_TEACHER_LEADER_FAILURE";

export const CHOOSE_STUDENT_REQUEST = "CHOOSE_STUDENT_REQUEST";
export const CHOOSE_STUDENT_SUCCESS = "CHOOSE_STUDENT_SUCCESS";
export const CHOOSE_STUDENT_FAILURE = "CHOOSE_STUDENT_FAILURE";

export const REMOVE_STUDENT_FROM_TEMPORARY_LIST_REQUEST =
  "REMOVE_STUDENT_FROM_TEMPORARY_LIST_REQUEST";
export const REMOVE_STUDENT_FROM_TEMPORARY_LIST_SUCCESS =
  "REMOVE_STUDENT_FROM_TEMPORARY_LIST_SUCCESS";
export const REMOVE_STUDENT_FROM_TEMPORARY_LIST_FAILURE =
  "REMOVE_STUDENT_FROM_TEMPORARY_LIST_FAILURE";

export const GET_ALL_INSTRUCTOS_BY_FACULTY_OF_TEACHER_LEADER_REQUEST =
  "GET_ALL_INSTRUCTOS_BY_FACULTY_OF_TEACHER_LEADER_REQUEST";
export const GET_ALL_INSTRUCTOS_BY_FACULTY_OF_TEACHER_LEADER_SUCCESS =
  "GET_ALL_INSTRUCTOS_BY_FACULTY_OF_TEACHER_LEADER_SUCCESS";
export const GET_ALL_INSTRUCTOS_BY_FACULTY_OF_TEACHER_LEADER_FAILURE =
  "GET_ALL_INSTRUCTOS_BY_FACULTY_OF_TEACHER_LEADER_FAILURE";

export const CHOOSE_INSTRUCTOR_REQUEST = "CHOOSE_INSTRUCTOR_REQUEST";
export const CHOOSE_INSTRUCTOR_SUCCESS = "CHOOSE_INSTRUCTOR_SUCCESS";
export const CHOOSE_INSTRUCTOR_FAILURE = "CHOOSE_INSTRUCTOR_FAILURE";

export const REMOVE_INSTRUCTOR_REQUEST = "REMOVE_INSTRUCTOR_REQUEST";
export const REMOVE_INSTRUCTOR_SUCCESS = "REMOVE_INSTRUCTOR_SUCCESS";
export const REMOVE_INSTRUCTOR_FAILURE = "REMOVE_INSTRUCTOR_FAILURE";

export const ASSIGN_INSTRUCTOR_REQUEST = "ASSIGN_INSTRUCTOR_REQUEST";
export const ASSIGN_INSTRUCTOR_SUCCESS = "ASSIGN_INSTRUCTOR_SUCCESS";
export const ASSIGN_INSTRUCTOR_FAILURE = "ASSIGN_INSTRUCTOR_FAILURE";

export const GET_ALL_STUDENTS_HAVING_INSTRUCTOR_BY_FACULTY_REQUEST =
  "GET_ALL_STUDENTS_HAVING_INSTRUCTOR_BY_FACULTY_REQUEST";
export const GET_ALL_STUDENTS_HAVING_INSTRUCTOR_BY_FACULTY_SUCCESS =
  "GET_ALL_STUDENTS_HAVING_INSTRUCTOR_BY_FACULTY_SUCCESS";
export const GET_ALL_STUDENTS_HAVING_INSTRUCTOR_BY_FACULTY_FAILURE =
  "GET_ALL_STUDENTS_HAVING_INSTRUCTOR_BY_FACULTY_FAILURE";

export const REMOVE_INSTRUCTOR_FROM_STUDENT_REQUEST =
  "REMOVE_INSTRUCTOR_FROM_STUDENT_REQUEST";
export const REMOVE_INSTRUCTOR_FROM_STUDENT_SUCCESS =
  "REMOVE_INSTRUCTOR_FROM_STUDENT_SUCCESS";
export const REMOVE_INSTRUCTOR_FROM_STUDENT_FAILURE =
  "REMOVE_INSTRUCTOR_FROM_STUDENT_FAILURE";

export const CHANGE_INSTRUCTOR_OF_STUDENT_REQUEST =
  "CHANGE_INSTRUCTOR_OF_STUDENT_REQUEST";
export const CHANGE_INSTRUCTOR_OF_STUDENT_SUCCESS =
  "CHANGE_INSTRUCTOR_OF_STUDENT_SUCCESS";
export const CHANGE_INSTRUCTOR_OF_STUDENT_FAILURE =
  "CHANGE_INSTRUCTOR_OF_STUDENT_FAILURE";

export const GET_ALL_PROJECTS_REQUEST = "GET_ALL_PROJECTS_REQUEST";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
export const GET_ALL_PROJECTS_FAILURE = "GET_ALL_PROJECTS_FAILURE";

export const GET_ALL_PROJECTS_FOR_EXPORT_REQUEST =
  "GET_ALL_PROJECTS_FOR_EXPORT_REQUEST";
export const GET_ALL_PROJECTS_FOR_EXPORT_SUCCESS =
  "GET_ALL_PROJECTS_FOR_EXPORT_SUCCESS";
export const GET_ALL_PROJECTS_FOR_EXPORT_FAILURE =
  "GET_ALL_PROJECTS_FOR_EXPORT_FAILURE";
