export const GET_ALL_SEMESTER_REQUEST = "GET_ALL_SEMESTER_REQUEST";
export const GET_ALL_SEMESTER_SUCCESS = "GET_ALL_SEMESTER_SUCCESS";
export const GET_ALL_SEMESTER_FAILURE = "GET_ALL_SEMESTER_FAILURE";

export const CREATE_SEMESTER_REQUEST = "CREATE_SEMESTER_REQUEST";
export const CREATE_SEMESTER_SUCCESS = "CREATE_SEMESTER_SUCCESS";
export const CREATE_SEMESTER_FAILURE = "CREATE_SEMESTER_FAILURE";

export const DELETE_SEMESTER_REQUEST = "DELETE_SEMESTER_REQUEST";
export const DELETE_SEMESTER_SUCCESS = "DELETE_SEMESTER_SUCCESS";
export const DELETE_SEMESTER_FAILURE = "DELETE_SEMESTER_FAILURE";

export const GET_SEMESTER_BY_ID_REQUEST = "GET_SEMESTER_BY_ID_REQUEST";
export const GET_SEMESTER_BY_ID_SUCCESS = "GET_SEMESTER_BY_ID_SUCCESS";
export const GET_SEMESTER_BY_ID_FAILURE = "GET_SEMESTER_BY_ID_FAILURE";

export const UPDATE_SEMESTER_BY_ID_REQUEST = "UPDATE_SEMESTER_BY_ID_REQUEST";
export const UPDATE_SEMESTER_BY_ID_SUCCESS = "UPDATE_SEMESTER_BY_ID_SUCCESS";
export const UPDATE_SEMESTER_BY_ID_FAILURE = "UPDATE_SEMESTER_BY_ID_FAILURE";

export const GET_ALL_SEMESTER_WITHOUT_PAGINATION_REQUEST =
  "GET_ALL_SEMESTER_WITHOUT_PAGINATION_REQUEST";
export const GET_ALL_SEMESTER_WITHOUT_PAGINATION_SUCCESS =
  "GET_ALL_SEMESTER_WITHOUT_PAGINATION_SUCCESS";
export const GET_ALL_SEMESTER_WITHOUT_PAGINATION_FAILURE =
  "GET_ALL_SEMESTER_WITHOUT_PAGINATION_FAILURE";
