export const CREATE_STAGE_REQUEST = "CREATE_STAGE_REQUEST";
export const CREATE_STAGE_SUCCESS = "CREATE_STAGE_SUCCESS";
export const CREATE_STAGE_FAILURE = "CREATE_STAGE_FAILURE";

export const UPDATE_STAGE_REQUEST = "UPDATE_STAGE_REQUEST";
export const UPDATE_STAGE_SUCCESS = "UPDATE_STAGE_SUCCESS";
export const UPDATE_STAGE_FAILURE = "UPDATE_STAGE_FAILURE";

export const DELETE_STAGE_REQUEST = "DELETE_STAGE_REQUEST";
export const DELETE_STAGE_SUCCESS = "DELETE_STAGE_SUCCESS";
export const DELETE_STAGE_FAILURE = "DELETE_STAGE_FAILURE";

export const GET_ALL_STAGES_BY_INSTRUCTOR_AND_SEMESTER_REQUEST =
  "GET_ALL_STAGES_BY_INSTRUCTOR_AND_SEMESTER_REQUEST";
export const GET_ALL_STAGES_BY_INSTRUCTOR_AND_SEMESTER_SUCCESS =
  "GET_ALL_STAGES_BY_INSTRUCTOR_AND_SEMESTER_SUCCESS";
export const GET_ALL_STAGES_BY_INSTRUCTOR_AND_SEMESTER_FAILURE =
  "GET_ALL_STAGES_BY_INSTRUCTOR_AND_SEMESTER_FAILURE";

export const GET_STAGE_BY_ID_REQUEST = "GET_STAGE_BY_ID_REQUEST";
export const GET_STAGE_BY_ID_SUCCESS = "GET_STAGE_BY_ID_SUCCESS";
export const GET_STAGE_BY_ID_FAILURE = "GET_STAGE_BY_ID_FAILURE";

export const DELETE_STAGEFILE_BY_STAGEFILEID_REQUEST =
  "DELETE_STAGEFILE_BY_STAGEFILEID_REQUEST";
export const DELETE_STAGEFILE_BY_STAGEFILEID_SUCCESS =
  "DELETE_STAGEFILE_BY_STAGEFILEID_SUCCESS";
export const DELETE_STAGEFILE_BY_STAGEFILEID_FAILURE =
  "DELETE_STAGEFILE_BY_STAGEFILEID_FAILURE";

export const GET_ALL_STAGESTATUSES_REQUEST = "GET_ALL_STAGESTATUSES_REQUEST";
export const GET_ALL_STAGESTATUSES_SUCCESS = "GET_ALL_STAGESTATUSES_SUCCESS";
export const GET_ALL_STAGESTATUSES_FAILURE = "GET_ALL_STAGESTATUSES_FAILURE";

export const UPDATE_STAGESTATUS_REQUEST = "UPDATE_STAGESTATUS_REQUEST";
export const UPDATE_STAGESTATUS_SUCCESS = "UPDATE_STAGESTATUS_SUCCESS";
export const UPDATE_STAGESTATUS_FAILURE = "UPDATE_STAGESTATUS_FAILURE";

export const UPDATE_STAGEORDER_REQUEST = "UPDATE_STAGEORDER_REQUEST";
export const UPDATE_STAGEORDER_SUCCESS = "UPDATE_STAGEORDER_SUCCESS";
export const UPDATE_STAGEORDER_FAILURE = "UPDATE_STAGEORDER_FAILURE";
